openapi: 3.0.0
info:
  title: Behavioral Tracking API
  description: 'Our Behavioral Tracking API is used to identify and track customer data with Customer.io. You can add and delete customers and their devices, supress and unsupress customers, as well as manage events and segments (manually added customers from GUI interface). Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `Behavioral Tracking API` only. `BETA API` integration will be available soon. This sample authorizes using my demo tracking API keys.<br/><br/> **Note**: `id` parameter is required for all endpoints.'
  version: '1.0'
  termsOfService: 'https://customer.io/legal/terms-of-service/'
  contact:
    name: Customer.io
    url: 'https://customer.io/contact/'
    email: support@customer.io.com
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://customer.io/pricing/'
servers:
  - url: 'https://track.customer.io/api/v1'
    description: Behavioral Tracking API
paths:
  '/customers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: User's unique ID
    put:
      summary: ''
      operationId: put-customers-id
      parameters:
        - schema:
            type: string
            default: application/x-www-form-urlencoded
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            default: Basic MDc4ZjA5YjkyNGMxNTYxYTAwMzA6ZmEyNDY2YWE0NDYyNDBjNDNiMzE=
          in: header
          name: Authorization
      description: Create or update a customer.
      responses: {}
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: someemail
                created_at:
                  type: integer
                  default: asdfasdfasdf
              required:
                - email
    delete:
      summary: ''
      operationId: delete-customers-id
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    MDc4ZjA5YjkyNGMxNTYxYTAwMzA6ZmEyNDY2YWE0NDYyNDBjNDNiMzE=:
      type: http
      scheme: basic
security:
  - authorization: []
